name: Sync (/ to adamlui/chatgpt-apps/bravegpt/) && (/greasemonkey/ to adamlui/userscripts/chatgpt/bravegpt/)

on:
  push:
    branches: [ master, main ]
    paths:
      - '**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout kudoai/bravegpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/bravegpt
          path: kudoai/bravegpt

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync README.md between directories
        run: |
          if [ "$(stat -c %y "${{ github.workspace }}/kudoai/bravegpt/README.md")" > "$(stat -c %y "${{ github.workspace }}/kudoai/bravegpt/greasemonkey/README.md")" ]; then
            cp -f "${{ github.workspace }}/kudoai/bravegpt/README.md" "${{ github.workspace }}/kudoai/bravegpt/greasemonkey/README.md"
          elif [ "$(stat -c %y "${{ github.workspace }}/kudoai/bravegpt/greasemonkey/README.md")" > "$(stat -c %y "${{ github.workspace }}/kudoai/bravegpt/README.md")" ]; then
            cp -f "${{ github.workspace }}/kudoai/bravegpt/greasemonkey/README.md" "${{ github.workspace }}/kudoai/bravegpt/README.md"
          fi

      - name: Sync / to adamlui/chatgpt-apps/bravegpt/
        run: rsync -avhr --delete --exclude={'.*','package*json'} ${{ github.workspace }}/kudoai/bravegpt/ ${{ github.workspace }}/adamlui/chatgpt-apps/bravegpt/

      - name: Sync /greasemonkey/ to adamlui/userscripts/chatgpt/bravegpt/
        run: rsync -avhr --delete ${{ github.workspace }}/kudoai/bravegpt/greasemonkey/ ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/

      - name: Push to kudoai/bravegpt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/bravegpt`]'
          file_pattern: '**'
          repository: kudoai/bravegpt

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/bravegpt`]'
          file_pattern: 'bravegpt/**'
          repository: adamlui/chatgpt-apps

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/bravegpt`]'
          file_pattern: 'chatgpt/bravegpt/**'
          repository: adamlui/userscripts
