name: Sync greasemonkey to (adamlui/userscripts/chatgpt || adamlui/chatgpt-userscripts) /bravegpt

on:
  push:
    branches: [ master, main ]
    paths:
      - 'greasemonkey/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout kudoai/bravegpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/bravegpt
          path: kudoai/bravegpt

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-userscripts
          path: adamlui/chatgpt-userscripts

      - name: Copy greasemonkey/README.md to root directory
        run: cp -f ${{ github.workspace }}/kudoai/bravegpt/greasemonkey/README.md ${{ github.workspace }}/kudoai/bravegpt/README.md

      - name: Sync kudoai/bravegpt/greasemonkey to adamlui/userscripts/chatgpt/bravegpt
        run: rsync -av --delete ${{ github.workspace }}/kudoai/bravegpt/greasemonkey/ ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/

      - name: Sync kudoai/bravegpt/greasemonkey to adamlui/chatgpt-userscripts/bravegpt
        run: rsync -av --delete ${{ github.workspace }}/kudoai/bravegpt/greasemonkey/ ${{ github.workspace }}/adamlui/chatgpt-userscripts/bravegpt/

      - name: Push to kudoai/bravegpt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/bravegpt/greasemonkey`]'
          file_pattern: '*'
          repository: kudoai/bravegpt

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/bravegpt`]'
          file_pattern: 'chatgpt/bravegpt/*'
          repository: adamlui/userscripts

      - name: Push to adamlui/chatgpt-userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `kudoai/bravegpt`]'
          file_pattern: 'bravegpt/*'
          repository: adamlui/chatgpt-userscripts