name: Sync greasemonkey to adamlui/userscripts/chatgpt/bravegpt

on:
  push:
    branches:
      - main
    paths:
      - 'greasemonkey/**'
    if: 'github.event.head_commit.committer.username != "github-actions[bot]"'

jobs:
  sync-bravegpt:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout kudoai/bravegpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/bravegpt
          path: kudoai/bravegpt

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync kudoai/bravegpt/greasemonkey to adamlui/userscripts/chatgpt/bravegpt
        run: rsync -av --delete ${{ github.workspace }}/kudoai/bravegpt/greasemonkey/ ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_name: 'auto-sync[bot]'
          commit_message: '${{ github.event.head_commit.message }} ← `kudoai/bravegpt` auto-sync'
          file_pattern: 'chatgpt/bravegpt/*'
          repository: adamlui/userscripts