name: Sync greasemonkey to adamlui/userscripts/chatgpt/bravegpt

on:
  push:
    branches:
      - main
    paths:
      - 'greasemonkey/**'
    if: 'github.actor != "auto-sync[bot]"'

jobs:
  sync-bravegpt:
    runs-on: ubuntu-latest
    steps:

      # Checkout adamlui/bravegpt
      - name: Checkout adamlui/bravegpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/bravegpt
          path: adamlui/bravegpt

      # Checkout adamlui/userscripts
      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      # Sync adamlui/bravegpt/greasemonkey to adamlui/userscripts/chatgpt/bravegpt
      - name: Sync bravegpt
        run: rsync -av --delete ${{ github.workspace }}/adamlui/bravegpt/greasemonkey/ ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/

      # Push to adamlui/userscripts
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_name: 'auto-sync[bot]'
          commit_message: '${{ github.event.head_commit.message }} (synced from adamlui/bravegpt)'
          file_pattern: 'chatgpt/bravegpt/*'
          repository: adamlui/userscripts
